name: build chromium for windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          choco install python3
          choco install depot_tools
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
          choco install windows-sdk-10-version-2004-all
      - name: Build Chromium
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH=$PATH:$PWD/depot_tools
          fetch --nohooks chromium
          cd src
          ./build/install-build-deps.bat --no-prompt --no-arm --no-nacl --no-backwards-compatible
          gn gen out/Default --args="is_debug=false"
          ninja -C out/Default chrome"
