name: build nginx for windows

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - uses: TheMrMilchmann/setup-msvc-dev@v2.0.0
        with:
          arch: x64
      - uses: msys2/setup-msys2@v2
      - name: copy source code
        run: |
          git clone https://github.com/nginx/nginx
          cd nginx
          mkdir objs
          cd objs
          mkdir lib
          cd lib
          git clone https://github.com/PCRE2Project/pcre2
          git clone https://github.com/madler/zlib
          git clone https://github.com/openssl/openssl
          cd ../../
          mkdir output
      - shell: msys2 {0}
        run: |
          cd ../../build/build/nginx
          ./auto/configure --with-cc=cl --with-debug --prefix= --conf-path=conf/nginx.conf --pid-path=logs/nginx.pid --http-log-path=logs/access.log --error-log-path=logs/error.log --sbin-path=nginx.exe --http-client-body-temp-path=temp/client_body_temp --http-proxy-temp-path=temp/proxy_temp --http-fastcgi-temp-path=temp/fastcgi_temp --http-scgi-temp-path=temp/scgi_temp --http-uwsgi-temp-path=temp/uwsgi_temp --with-cc-opt=-DFD_SETSIZE=1024 --with-pcre=objs/lib/pcre2 --with-zlib=objs/lib/zlib --with-openssl=objs/lib/openssl --with-openssl-opt=no-asm --with-http_ssl_module --with-stream_ssl_preread_module --builddir=output
      - name: make
        run: |
          cd nginx/output
          nmake
          cd ../
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: nginx-windows
          path: output/*
      
